language: generic
services: docker
install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "$DOCKER_HUB_PASSWORD" |
        docker login --username stephanmisc --password-stdin
    fi
    curl https://raw.githubusercontent.com/stepchowfun/toast/master/install.sh -LSfs |
      VERSION=0.28.0 sh
script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      WRITE_REMOTE_CACHE=true

      if [ "$TRAVIS_BRANCH" = "master" ]; then
        TOAST_TASK=publish
      else
        TOAST_TASK=build
      fi
    else
      WRITE_REMOTE_CACHE=false
      TOAST_TASK=build
    fi

    toast "$TOAST_TASK" \
      --repo stephanmisc/toast \
      --read-remote-cache true \
      --write-remote-cache "$WRITE_REMOTE_CACHE"
