name: Continuous integration
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: stephanmisc
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: github.event_name == 'push'
    - uses: stepchowfun/toast/.github/actions/toast@master
      with:
        tasks: publish
        repo: stephanmisc/toast
        write_remote_cache: true
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    - uses: stepchowfun/toast/.github/actions/toast@master
      with:
        tasks: build
        repo: stephanmisc/toast
        write_remote_cache: ${{ github.event_name == 'push' }}
      if: github.event_name == 'pull_request' || github.ref != 'refs/heads/master'
